eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

spring:
   application:
      name: book-store-inventory

server:
      port: 9002

ribbon:
      eureka:
         enable: true