eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

spring:
   application:
      name: book-store-customer

server:
      port: 9001

ribbon:
      eureka:
         enable: true

management.security.enabled : false